### ISSUE TITLE
Startup server incidence incidents

### ISSUE THREAD

**Issue by sebrobertssteer** [steerenergy/Datalogger-Alistair-Pi#23]
steerLogger1 - Error message: Server connection already in use. Happened when first setting up the logger, but then the issue went away for a while. It then suddenly (blame Mozza) started flashing this up, so now I every time I have to make sure all laptops in the vicinity aren't on the wifi.

![IMG_20211008_101940](https://user-images.githubusercontent.com/56635934/145969986-85b30991-c97f-4e5a-9c8c-1fefa8609e10.jpg)
l

**Comment by Alistair-L-R** [comment]
I have changed the way in which the logger program is started when the Pi is turned on, this should fix the issue. I have tested it a couple times and the error has not flashed up. If you do get the error again, let me know.

**Comment by sebrobertssteer** [comment]
Perfect, thanks bud

 

Sebastian Roberts

Steer Energy Solutions

 

mobile: +44 (0)7491 511133

email:    ***@***.***> ***@***.***

web:      <http://www.steerenergy.com/> www.steerenergy.com

Skype:  s.roberts_31

 

The information contained in this message is sent in the strictest confidence for the addressee only. It is intended only for the use of the addressee and may contain privileged information. If you have received this email in error you are requested to preserve its confidentiality and advise the sender of the error in transmission. It is the responsibility of the addressee to scan this email and any attachments for computer viruses or other defects. The sender does not accept liability for any loss or damage of any nature, however caused, which may result directly or indirectly from this email or any file attached. Thank You.
